### PR TITLE
constify many input parameters

### PR DESCRIPTION
**Pull request by ThinkOpenly**
(Also fixed a comment or two.)

Signed-off-by: Paul A. Clarke <pc@us.ibm.com>

### CODE REVIEW

**Comment by ThinkOpenly** [comment]
> Have you covered all files and functions to add 'const' or is this commit subset of the task?

I would not consider this exhaustive, although I did try to cover as much as easily possible, without changing the API, forcing app changes, or requiring awkward or significant changes to the code.

> There are few bitv_cb_t * cb, bitv_word * bvec variables in the files src/bitv.c src/bitv.h which need to be checked.

I found another call there, and will push another commit to address that.  Thanks!

> should we add 'const' in the following function too?
> src/sasalloc.h: SOMSASSetBlockSubType (SASBlockHeader* header

No.  "header" is modified in that function.

**Comment by RajalakshmiS** [comment]
LGTM

**Comment by ThinkOpenly** [comment]
Thanks, Raji!

**Comment by RajalakshmiS** [comment]
test

**Pull request closed without merging**
