### PR TITLE
Ultree new

### PR DESCRIPTION
**Pull request by munroesj52**

### CODE REVIEW

**Comment by rzinsly** [comment]
The code LGTM, but this PR was also created from a dirty tree and we only need 1eeb59a.

**Comment by munroesj52** [comment]
Damn, I don't know where this is coming. I have "reset" munroesj52/sphde multiple times and it is still there.

**Comment by munroesj52** [comment]
This is the reset plan after each merge to sphde/sphde/

$ cd ./forks/sphde
$ git remote add upstream https://github.com/sphde/sphde
$ git remote -v
origin	https://github.com/munroesj52/sphde.git (fetch)
origin	https://github.com/munroesj52/sphde.git (push)
upstream	https://github.com/sphde/sphde (fetch)
upstream	https://github.com/sphde/sphde (push)

...
$ git fetch upstream
$ git checkout master
$ git merge upstream/master
$ git push origin master

**Comment by rzinsly** [comment]
Your master tree is dirty: https://github.com/munroesj52/sphde/commits/master
You can create a clean branch tracking the upstream master, e.g.:
`git checkout -b upstream --track upstream/master`
cherry-pick 1eeb59a, and use that branch on this PR.

Or you can delete you master branch and replace with the upstream's:
```
git branch -D master
git checkout -b master --track upstream/master
```
And do the same.

**Comment by munroesj52** [comment]
Seems I need a little bit more context ...
It will not allow the -D
$ git branch -D master
error: Cannot delete branch 'master' checked out at
'/home/sjmunroe/work/github/forks/sphde'

Nor will it allow the checkout option

$ git checkout -b upstream --track upstream/master
https://github.com/munroesj52/sphde
fatal: not a git repository (or any of the parent directories): .git

$ git checkout -b upstream --track upstream/master
fatal: 'upstream/master' is not a commit and a branch 'upstream' cannot be
created from it

Exactly where / should I be when I do these special things?

**Comment by rzinsly** [comment]
> Seems I need a little bit more context ...
>It will not allow the -D
>$ git branch -D master
>error: Cannot delete branch 'master' checked out at
>'/home/sjmunroe/work/github/forks/sphde'

This is new to me, I don't know why it doesn't let you delete it

>$ git checkout -b upstream --track upstream/master
>https://github.com/munroesj52/sphde
>fatal: not a git repository (or any of the parent directories): .git
>

Here it seems you are not at the directory with the git tree.

>$ git checkout -b upstream --track upstream/master
>fatal: 'upstream/master' is not a commit and a branch 'upstream' cannot be
>created from it

Note that I used `upstream` in my example because I assumed you had an upstream remote per your other comment:
>$ git remote add upstream https://github.com/sphde/sphde

Anyway, I can push only the last commit to the repo as I did last time, however any pull request you open based in your master will have these unnecessary commits with it.
If you can't clear it, maybe it is better to just clone the upstream repo in another directory and force push the master branch to your fork.

**Comment by tuliom** [comment]
> > Seems I need a little bit more context ...
> > It will not allow the -D
> > $ git branch -D master
> > error: Cannot delete branch 'master' checked out at
> > '/home/sjmunroe/work/github/forks/sphde'
> 
> This is new to me, I don't know why it doesn't let you delete it

Before you delete a branch, you have to checkout another branch.
I'd solve this issue this way:

```
git stash save # Save any uncommitted changes
git tag backup # Put a tag to guarantee we can recover data if necessary
git checkout master
git fetch upstream
git reset --hard upstream/master # Delete all the local changes.
git push -f origin master # Delete all remote changes in origin/master
git stash pop # Restore uncommitted changes
```

Notice this is going to overwrite your master branch here https://github.com/munroesj52/sphde
It may also overwrite local changes that can be recovered in the stash area (in case they haven't been committed) or in the `backup` tag.

After doing this, you need to change this PR:

```
git co ultree-new
git rebase -i master
# `git-rebase` interactive mode will allow you to remove unwanted commits by commenting their lines.
git push -f origin ultree-new
```

I also suggest to use `git merge --ff-only` in your master branch in order to avoid these unintentional merge commits.

**Pull request closed without merging**
