### PR TITLE
add support for loongarch

### PR DESCRIPTION
**Pull request by wuruilong01**

### CODE REVIEW

**Comment by munroesj52** [comment]
First some questions:

- loonarch is risk-v?
- What level of GCC are you using?
- By default sphde will use sasatom_generic.h which assumes the "built-in Functions for Memory Model Aware Atomic
Operations"?
- And you have verified that that address ranges you selected in sasconf.h do not conflict with normal kernel, SO  library, and heap allocations for your platform?

**Comment by wuruilong01** [comment]
* loongarch is not a risk-v
* gcc (Debian 13.2.0-5) 13.2.0

**Comment by wuruilong01** [comment]
* By default sphde will use sasatom_generic.h which assumes the "built-in Functions for Memory Model Aware Atomic
Operations"?
**Sorry, I couldn't understand this question.**

**Comment by wuruilong01** [comment]
* And you have verified that that address ranges you selected in sasconf.h do not conflict with normal kernel, SO library, and heap allocations for your platform?

**I did a simple run test and this is the memory layout of the loongarch machine
[root@localhost ~]# cat /proc/self/maps
aaac12c000-aaac138000 r-xp 00000000 fd:00 4462642                        /usr/bin/cat
aaac138000-aaac13c000 r--p 00008000 fd:00 4462642                        /usr/bin/cat
aaac13c000-aaac140000 rw-p 0000c000 fd:00 4462642                        /usr/bin/cat
aae9868000-aae988c000 rw-p 00000000 00:00 0                              [heap]
fff0ea0000-fff0ec8000 rw-p 00000000 00:00 0 
fff0ec8000-fff20f0000 r--p 00000000 fd:00 4458440                        /usr/lib/locale/locale-archive
fff20f0000-fff2258000 r-xp 00000000 fd:00 4458851                        /usr/lib64/libc.so.6
fff2258000-fff225c000 r--p 00164000 fd:00 4458851                        /usr/lib64/libc.so.6
fff225c000-fff2260000 rw-p 00168000 fd:00 4458851                        /usr/lib64/libc.so.6
fff2260000-fff226c000 rw-p 00000000 00:00 0 
fff2274000-fff2298000 r-xp 00000000 fd:00 4458847                        /usr/lib64/ld-linux-loongarch-lp64d.so.1
fff2298000-fff229c000 r--p 00020000 fd:00 4458847                        /usr/lib64/ld-linux-loongarch-lp64d.so.1
fff229c000-fff22a0000 rw-p 00024000 fd:00 4458847                        /usr/lib64/ld-linux-loongarch-lp64d.so.1
fffbaa0000-fffbac4000 rw-p 00000000 00:00 0                              [stack]
fffd724000-fffd72c000 r--p 00000000 00:00 0                              [vvar]
fffd72c000-fffd730000 r-xp 00000000 00:00 0                              [vdso]**

**Comment by wuruilong01** [comment]
* Is your hardware multi-core. Single core systesm might need some __sched_yield work arounds.
**multi-core**

**Comment by wuruilong01** [comment]
cpuinfo is as follows
`system type		: generic-loongson-machine
processor		: 0
package			: 0
core			: 0
cpu family		: Loongson-64bit
model name		: Loongson-3A5000-HV
CPU Revision		: 0x11
FPU Revision		: 0x00
CPU MHz			: 2500.00
BogoMIPS		: 5000.00
TLB entries		: 2112
Address sizes		: 48 bits physical, 48 bits virtual
isa			: loongarch32 loongarch64
features		: cpucfg lam ual fpu lsx lasx crc32 complex crypto lvz lbt_x86 lbt_arm lbt_mips
hardware watchpoint	: yes, iwatch count: 8, dwatch count: 8

processor		: 1
package			: 0
core			: 1
cpu family		: Loongson-64bit
model name		: Loongson-3A5000-HV
CPU Revision		: 0x11
FPU Revision		: 0x00
CPU MHz			: 2500.00
BogoMIPS		: 5000.00
TLB entries		: 2112
Address sizes		: 48 bits physical, 48 bits virtual
isa			: loongarch32 loongarch64
features		: cpucfg lam ual fpu lsx lasx crc32 complex crypto lvz lbt_x86 lbt_arm lbt_mips
hardware watchpoint	: yes, iwatch count: 8, dwatch count: 8

processor		: 2
package			: 0
core			: 2
cpu family		: Loongson-64bit
model name		: Loongson-3A5000-HV
CPU Revision		: 0x11
FPU Revision		: 0x00
CPU MHz			: 2500.00
BogoMIPS		: 5000.00
TLB entries		: 2112
Address sizes		: 48 bits physical, 48 bits virtual
isa			: loongarch32 loongarch64
features		: cpucfg lam ual fpu lsx lasx crc32 complex crypto lvz lbt_x86 lbt_arm lbt_mips
hardware watchpoint	: yes, iwatch count: 8, dwatch count: 8

processor		: 3
package			: 0
core			: 3
cpu family		: Loongson-64bit
model name		: Loongson-3A5000-HV
CPU Revision		: 0x11
FPU Revision		: 0x00
CPU MHz			: 2500.00
BogoMIPS		: 5000.00
TLB entries		: 2112
Address sizes		: 48 bits physical, 48 bits virtual
isa			: loongarch32 loongarch64
features		: cpucfg lam ual fpu lsx lasx crc32 complex crypto lvz lbt_x86 lbt_arm lbt_mips
hardware watchpoint	: yes, iwatch count: 8, dwatch count: 8`

**Comment by munroesj52** [comment]
>>By default sphde will use sasatom_generic.h which assumes the "built-in Functions for Memory Model Aware Atomic
Operations"?

Does the compiler for loogarch support the builtin atomic memory operations described in [6.55 Built-in Functions for Memory Model Aware Atomic Operations](https://gcc.gnu.org/onlinedocs/gcc-13.2.0/gcc/_005f_005fatomic-Builtins.html)

**Comment by munroesj52** [comment]
Looks like the BASE address and region size are safe.

**Comment by munroesj52** [comment]
So loongArch is "MIPS-compatible" with extensions. I have no way to test  loongArch, so you are responsible for any testing and verification on that platform.

**Comment by wuruilong01** [comment]
> So loongArch is "MIPS-compatible" with extensions. I have no way to test loongArch, so you are responsible for any testing and verification on that platform.

Encountered an error during the execution of unit tests, currently analyzing and resolving it.
```
make  check-TESTS
make[2]: Entering directory '/home/debian-build/wuruilong/push/sphde/src'
make[3]: Entering directory '/home/debian-build/wuruilong/push/sphde/src'
SKIP: sphgtod_t
SKIP: sphgettime_t
PASS: sasatom_t
PASS: bitvec_t
Terminated
make[3]: *** [Makefile:1913: sassim_t.log] Error 124
make[3]: Leaving directory '/home/debian-build/wuruilong/push/sphde/src'
make[2]: *** [Makefile:1867: check-TESTS] Error 2
make[2]: Leaving directory '/home/debian-build/wuruilong/push/sphde/src'
make[1]: *** [Makefile:2102: check-am] Error 2
make[1]: Leaving directory '/home/debian-build/wuruilong/push/sphde/src'
make: *** [Makefile:544: check-recursive] Error 1

```

**Comment by munroesj52** [comment]
Any luck with debug?
sassim_t is the first test that attempt memory operations (mmap and shmmap).

Also for make check, unit-test runs the script sassim_t that loads the DLL ./src/.libs/libsphde.so.
This can complicate debug. 

If this is a problem, you can try manually linking test-cases (ie ./src/tests/sassim_t.o) to the static library ./src/.libs/libsphde.a.

**Comment by wuruilong01** [comment]
I'm sorry, I've been busy with other things recently. I will try to resolve the unit testing error bug next week.

**Comment by wuruilong01** [comment]
I've resolved the compilation error for the bitvec_t unit test, but I'm encountering the following error. Do you have any suggestions?
```SKIP: sphgtod_t
SKIP: sphgettime_t
PASS: sasatom_t
PASS: bitvec_t
PASS: sassim_t
PASS: sascompoundheap_t
PASS: sasseg_t
PASS: sphlockfreeheap_t
PASS: sphlflogger_t
PASS: sphthread_t
PASS: sphlflogger_tt
PASS: sphlflogger_ttt
PASS: sphlogportal_t
PASS: sphlogportal_tt
PASS: sphcontext_t
PASS: sasindex_t
PASS: sasindex_tt
PASS: sasstringbtree_t
PASS: sasstringbtree_tt
PASS: sphsinglepcqueue_t
PASS: sphsinglepcqueue_tt
Terminated
make[3]: *** [Makefile:2032: sphsinglepcqueue_ttt.log] Error 124
make[3]: Leaving directory '/home/debian-build/wuruilong/push/sphde/src'
make[2]: *** [Makefile:1867: check-TESTS] Error 2
make[2]: Leaving directory '/home/debian-build/wuruilong/push/sphde/src'
make[1]: *** [Makefile:2102: check-am] Error 2
make[1]: Leaving directory '/home/debian-build/wuruilong/push/sphde/src'
make: *** [Makefile:544: check-recursive] Error 1
```

**Comment by munroesj52** [comment]
The Producer/Consumer Queues make assumptions about memory consistency and the atomicity of aligned pointer sized load/stores.

It might help if you shared the ./src/sphsinglepcqueue_tt.log from the failed run.

As i don't know the specifices of loongarch I can only suggest that you need to take a closer look. 

You may need a sronger version of __arch_pause for you platform. This would require your own sasatom_loongarch.h

**Comment by wuruilong01** [comment]
Thank you for your advice. I will carefully review the error message and attempt to resolve the issue by adding the sasatom_loongarch.h file.

**Comment by wuruilong01** [comment]
Thank you for your help @munroesj52 . I have resolved the issue and resubmitted the code. Here are the unit test results:
```
SKIP: sphgtod_t
SKIP: sphgettime_t
PASS: sasatom_t
PASS: bitvec_t
PASS: sassim_t
PASS: sascompoundheap_t
PASS: sasseg_t
PASS: sphlockfreeheap_t
PASS: sphlflogger_t
PASS: sphthread_t
PASS: sphlflogger_tt
PASS: sphlflogger_ttt
PASS: sphlogportal_t
PASS: sphlogportal_tt
PASS: sphcontext_t
PASS: sasindex_t
PASS: sasindex_tt
PASS: sasstringbtree_t
PASS: sasstringbtree_tt
PASS: sphsinglepcqueue_t
PASS: sphsinglepcqueue_tt
PASS: sphsinglepcqueue_ttt
PASS: sphdirectpcqueue_ttt
============================================================================
Testsuite summary for libsphde 1.4.0
============================================================================
# TOTAL: 23
# PASS:  21
# SKIP:  2
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

**Comment by munroesj52** [comment]
A nit but for consistency in ./src/sasatom_loongarch.h
s/_SASATOMIC_GENERIC_H/_SASATOMIC_LOONGARCH_H/

With this change I will merge.

**Comment by wuruilong01** [comment]
> A nit but for consistency in ./src/sasatom_loongarch.h s/_SASATOMIC_GENERIC_H/_SASATOMIC_LOONGARCH_H/
> 
> With this change I will merge.

Thank you for the code review; I have made the suggested changes.

**Comment by munroesj52** [comment]
Please review and if you can test on your platform.

https://github.com/sphde/sphde/pull/75

thanks

**Pull request merged**
