### PR TITLE
Gcc11 init

### PR DESCRIPTION
**Pull request by munroesj52**

### CODE REVIEW

**Comment by munroesj52** [comment]
Ya not sure where that came from.

**Comment by munroesj52** [comment]
I don't have access to GCC11 yet, Can you test it there?

**Comment by rzinsly** [comment]
> I don't have access to GCC11 yet, Can you test it there?

I tested and it is working.
Can we merge just fe7264ddd55d9c54b5da1eb2b16571f211dc7c46 ?

**Comment by munroesj52** [comment]
Looks like my fork was dirty with old patches. I reset/restart.

**Comment by munroesj52** [comment]
A cleaner patch
https://github.com/sphde/sphde/pull/55

**Pull request closed without merging**
